### PR TITLE
While I am waiting for BTM16 client restarting...

### PR DESCRIPTION
**Pull request by 3TUSK**
Update zh_CN.lang.
Summary:
Correct some minor mistakes, also update several entries.

### CODE REVIEW

**Comment by Adaptivity** [comment]
@mezz I think you should give @3TUSK push access to this repository since now he mostly maintaining Chinese localizations for MC mods.

**Comment by mezz** [comment]
Sounds good, they have been invited.

**Comment by 3TUSK** [comment]
@mezz @Adaptivity I have seen your email and I accepted your invitation. Appreciation to you guys!
Btw I saw @mezz in BTM16, and I wonder if @Adaptivity you are there?

**Comment by Adaptivity** [comment]
Nope, I'm not on BTM16. I have no time to play MC, too busy with things in real life :(

**Comment by 3TUSK** [comment]
Ahh sorry to here that. Anyway hope everything is good.

**Pull request merged**
